[2023-12-13T07:43:32.019+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v1.create_postgres_table manual__2023-12-13T07:36:54.483960+00:00 [queued]>
[2023-12-13T07:43:32.044+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v1.create_postgres_table manual__2023-12-13T07:36:54.483960+00:00 [queued]>
[2023-12-13T07:43:32.044+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 6
[2023-12-13T07:43:32.117+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-12-13 07:36:54.483960+00:00
[2023-12-13T07:43:32.132+0000] {standard_task_runner.py:57} INFO - Started process 466 to run task
[2023-12-13T07:43:32.226+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v1', 'create_postgres_table', 'manual__2023-12-13T07:36:54.483960+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/dag_w_postgres_operator.py', '--cfg-path', '/tmp/tmpdt3wgmw2']
[2023-12-13T07:43:32.241+0000] {standard_task_runner.py:85} INFO - Job 164: Subtask create_postgres_table
[2023-12-13T07:43:32.573+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table manual__2023-12-13T07:36:54.483960+00:00 [running]> on host 6bd2d0daa4c2
[2023-12-13T07:43:32.852+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vuhta' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v1' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T07:36:54.483960+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-13T07:36:54.483960+00:00'
[2023-12-13T07:43:32.853+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-12-13T07:43:32.892+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-13T07:43:32.944+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-13T07:43:32.959+0000] {sql.py:418} INFO - Running statement: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2023-12-13T07:43:32.993+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v1, task_id=create_postgres_table, execution_date=20231213T073654, start_date=20231213T074332, end_date=20231213T074332
[2023-12-13T07:43:33.063+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-13T07:43:33.128+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
